SET DATEFORMAT DMY

CREATE DATABASE QLTG
USE QLTG

CREATE TABLE NGUOIDUNG
(
	HO NVARCHAR(40),
	TEN NVARCHAR(10),
	GIOITINH BIT,
	NGAYSINH date,
	DIACHI NVARCHAR(50),
	CONSTRAINT NGUOIDUNG_TEN_PK PRIMARY KEY(TEN)
)

SELECT *
FROM NGUOIDUNG

CREATE TABLE THONGTINTK
(
	TENTK NVARCHAR(30),
	MATKHAU NVARCHAR(20),
	CONSTRAINT THONGTINTK_TENTK_PK PRIMARY KEY(TENTK)
)

CREATE TABLE PHANQUYEN
(
	TEN NVARCHAR(5),
	CONSTRAINT PHANQUYEN_TEN_PK PRIMARY KEY(TEN)
)

CREATE TABLE CONGVIEC
(
	TENCV NVARCHAR(50),
	THOIGIANBD DATETIME,
	THOIGIANKT DATETIME,
	TRANGTHAI NVARCHAR(5),
	DIADIEM NVARCHAR(50),
	GHICHU NVARCHAR(100),
	CONSTRAINT CONGVIEC_TENCV_PK PRIMARY KEY(TENCV)	
)
CREATE TABLE SUKIEN
(
	TENSK NVARCHAR(50),
	THOIGIANBD DATETIME,
	THOIGIANKT DATETIME,
	TRANGTHAI NVARCHAR(5),
	DIADIEM NVARCHAR(50),
	GHICHU NVARCHAR(100),
	CONSTRAINT SUKIEN_TENSK_PK PRIMARY KEY(TENSK)
)

CREATE TABLE LICH
(
    DMY DATE,
	HMS TIME,
	CONSTRAINT LICH_DMY_HMS_PK PRIMARY KEY(DMY,HMS)
)

CREATE TABLE NHACNHO
(
	TEN NVARCHAR(20),
	NOIDUNG NVARCHAR(50),
	THOIGIAN DATETIME,
	TRANGTHAI NVARCHAR(5),
	CONSTRAINT NHACNHO_TEN_PK PRIMARY KEY(TEN)
)
